const artists = [
  {
    image: 'https://b6c18f286245704fe3e9-05e2055f4cd9122af02914269431c9f6.ssl.cf1.rackcdn.com/6373260_future-stars-lany-polydor_b0787513_m.jpg?bg=435062',
    start: '12:45',
    end: '13:35',
    name: 'Lany',
    description: 'LANY formed in March 2014 when Paul Klein, who had a small solo career, flew to Nashville to meet up with Jake Goss and Les Priest. Previously, Goss and Priest had a separate project by the name of WRLDS, but this was discontinued after the formation of LANY. The following month they uploaded two songs, \'Hot Lights\' and \'Walk Away\', to SoundCloud incognito in order to differentiate between their old and new projects. Their debut EP, \'Acronymns\' followed later that year, with song \'ILYSB\' generating significant traffic online. Singles \'Made In Hollywood\' and \'Bad, Bad, Bad\' soon followed, along with the reveal of their identities.',
    stage: 'Lands End',
    genre: 'Indie Pop',
    upvotes: 3471,
    events: 1,
    followers: 2130,
    album: 'Make Out',
    time: 'Friday, 1245PM',
  },
  {
    image: 'http://thekey.xpn.org/aatk/files/2013/06/ra-ra-riot.jpg',
    start: '14:05',
    end: '14:55',
    name: 'Ra Ra Riot',
    description: 'Ra Ra Riot is an American indie rock band from Syracuse, New York, consisting of vocalist Wes Miles, bassist Mathieu Santos, guitarist Milo Bonacci, violinist Rebecca Zeller and drummer Kenny Bernard.',
    stage: 'Lands End',
    genre: 'Indie Rock',
    upvotes: 2875,
    events: 1,
    followers: 1630,
    album: 'Need Your Light',
    time: 'Friday, 205PM',
  },
  {
    image: 'http://aaabackstage.com/aaa_2015/wp-content/uploads/2016/02/St-Lucia-Album-Review.jpg',
    start: '15:25',
    end: '16:15',
    name: 'St. Lucia',
    description: 'Jean-Philip Grobler, known by his stage name St. Lucia, is a South African-born, Brooklyn-based musician. He is signed to Columbia Records and to date has released two albums; When the Night (2013) and Matter (2016).',
    stage: 'Lands End',
    genre: 'Indie Electronic',
    upvotes: 2275,
    events: 1,
    followers: 1889,
    album: 'Matter',
    time: 'Friday, 325PM',
  },
  {
    image: 'http://cheeseontoast.co.nz/wp-content/uploads/2016/04/1401x788-Miike-Snow-Main-Pub-Photo_Photo-Credit-Nick-Zinner_Henrik-Korpi_Joachim-Belaieff.jpg',
    start: '16:45',
    end: '17:45',
    name: 'Miike Snow',
    description: 'Miike Snow (pronounced maɪk sno) is a Swedish indie pop band formed in 2007. The band consists of producing team Bloodshy & Avant and singer Andrew Wyatt. The band is often represented by a silhouette image of a jackalope. Since their debut, they have released three studio albums: Miike Snow (2009), Happy to You (2012), and iii (2016).',
    stage: 'Lands End',
    genre: 'Indie Pop',
    upvotes: 3175,
    events: 1,
    followers: 2431,
    album: 'iii',
    time: 'Friday, 445PM',
  },
  {
    image: 'http://duranduran.warnereprise.com/images/mobbg.jpg',
    start: '18:15',
    end: '19:25',
    name: 'Duran Duran',
    description: 'Duran Duran are an English new wave/synthpop band formed in Birmingham in 1978. They were a successful band of the 1980s and a leading band in the MTV-driven "Second British Invasion" of the US. Since the 1980s, they have placed 14 singles in the Top 10 of the UK Singles Chart and 21 in the Billboard Hot 100, and have sold over 70 million records.',
    stage: 'Lands End',
    genre: 'New Wave',
    upvotes: 8979,
    events: 1,
    followers: 5837,
    album: 'Paper Gods',
    time: 'Friday, 615PM',
  },
  {
    image: 'http://static.spin.com/files/2015/12/lcd-soundsystem-coachella-2016.jpg',
    start: '20:10',
    end: '21:55',
    name: 'LCD Soundsystem',
    description: 'LCD Soundsystem is an American rock band from Brooklyn, New York. Formed in 2002, it is fronted by musician James Murphy, co-founder of DFA Records, the record label to which the band are signed (alongside Columbia Records). The band began by recording and releasing multiple singles from 2002 to 2004 leading up to their eponymous debut studio album, which was released in 2005. It garnered critical acclaim as well as a Grammy nomination for Best Electronic/Dance Album. Their single "Daft Punk Is Playing at My House", which has become the band\'s most successful single, also received a Grammy nomination for Best Dance Recording.',
    stage: 'Lands End',
    genre: 'American Rock',
    upvotes: 6379,
    events: 1,
    followers: 4237,
    album: 'This Is Happening',
    time: 'Friday, 810PM',
  },
  {
    image: 'http://www.publishedlive.com/wp-content/uploads/2016/06/2016_Whitney_PR_120216.jpg',
    start: '12:00',
    end: '12:45',
    name: 'Whitney',
    stage: 'Sutro',
    genre: 'Indie Rock',
    upvotes: 1179,
    events: 1,
    followers: 1945,
    album: 'Light Upon the Lake',
    time: 'Friday, 1200PM',
  },
  {
    image: 'http://thephoenix.com/secure/uploadedImages/The_Phoenix/Music/CD_Review/main_caveman_band480.jpg',
    start: '13:15',
    end: '14:00',
    name: 'Caveman',
    description: 'Caveman is an American band based in Brooklyn, New York. The band recorded their first studio album in 2011. Although originally self-released, the album was re-released by Fat Possum Records in 2012. Caveman performed at SXSW 2013[2] and Sasquatch Festival 2013. The band\'s musical style is a mixture of indie rock and indie pop. Caveman also performed at the latest Bonnaroo 2014 Arts and Music Festival.',
    stage: 'Sutro',
    genre: 'Indie Rock/Pop',
    upvotes: 2179,
    events: 1,
    followers: 2145,
    album: 'Otero War',
    time: 'Friday, 115PM',
  },
  {
    image: 'http://turksandunderdog.com/wp-content/uploads/2016/02/wet.jpg',
    start: '14:30',
    end: '15:20',
    name: 'Wet',
    description: 'Wet is an American indie pop group from Brooklyn, New York, consisting of Kelly Zutrau, Joe Valle, and Marty Sulkow. They have released both an EP and full-length album and are currently signed to Columbia Records. Wet was called the most promising group in music by The Fader in 2015',
    stage: 'Sutro',
    genre: 'Indie Pop',
    upvotes: 3140,
    events: 1,
    followers: 2935,
    album: 'Don\'t You',
    time: 'Friday, 230PM',
  },
  {
    image: 'http://static.spin.com/files/130213-foals.jpg',
    start: '15:50',
    end: '16:40',
    name: 'Foals',
    description: 'Foals are an English indie rock band from Oxford, England formed in 2005, consisting of lead vocalist and lead guitarist Yannis Philippakis, drummer and percussionist Jack Bevan, rhythm guitarist Jimmy Smith, bassist Walter Gervers and keyboardist Edwin Congreave. Since the band\'s formation, their line-up has remained constant.',
    stage: 'Sutro',
    genre: 'Indie Rock',
    upvotes: 2849,
    events: 1,
    followers: 2538,
    album: 'What Went Down',
    time: 'Friday, 350PM',
  },
  {
    image: 'https://consequenceofsound.files.wordpress.com/2016/01/screen-shot-2016-01-20-at-12-37-57-pm.png?w=797',
    start: '17:10',
    end: '18:00',
    name: 'The Claypool Lennon Delirium',
    description: 'On January 19, 2016, it was announced that The Claypool Lennon Delirium, a collaboration between Claypool and Sean Lennon, would debut at Bonnaroo 2016. Claypool has spoken fondly of the collaboration, stating, “Sean is a musical mutant after my own heart. He definitely reflects his genetics – not just the sensibilities of his dad, but also the abstract perspective and unique approach of his mother. It makes for a glorious freak stew.',
    stage: 'Sutro',
    genre: 'Indie Rock',
    upvotes: 2649,
    events: 1,
    followers: 2238,
    album: 'Monolith of Phobos',
    time: 'Friday, 510PM',
  },
  {
    image: 'http://static1.squarespace.com/static/554babe2e4b0e66924e4a375/t/55de47fae4b04e9d1062c77d/1440630779046/',
    start: '18:30',
    end: '19:20',
    name: 'Nathaniel Rateliff & The Night Sweats',
    description: 'Nathaniel David Rateliff is an American musician, singer and songwriter from Hermann, Missouri. Known for his folk-based, pensive songwriting, Rateliff has garnered attention with Nathaniel Rateliff & The Night Sweats, the soulful R&B combo he formed in 2013',
    stage: 'Sutro',
    genre: 'Folk',
    upvotes: 2649,
    events: 1,
    followers: 2238,
    album: 'Nathaniel Rateliff & the Night Sweats',
    time: 'Friday, 630PM',
  },
  {
    image: 'http://static.stereogum.com/uploads/2013/07/beachhouse.jpg',
    start: '19:50',
    end: '21:00',
    name: 'Beach House',
    description: 'Beach House is an American dream pop band from Baltimore, Maryland, formed in 2004. The band consists of French-born Victoria Legrand (vocals, keyboards) and Baltimore native Alex Scally (guitar, keyboards). Their self-titled debut album was released in 2006 to critical acclaim and has been followed by Devotion in 2008, Teen Dream in 2010, Bloom in 2012, and Depression Cherry and Thank Your Lucky Stars in 2015.',
    stage: 'Sutro',
    genre: 'Indie Rock',
    upvotes: 2949,
    events: 1,
    followers: 2638,
    album: 'Thank Your Lucky Stars',
    time: 'Friday, 750PM',
  },
  {
    image: 'http://blahblahblahscience.com/wp-content/uploads/2014/12/marianhill.jpg',
    start: '12:45',
    end: '13:30',
    name: 'Marian Hill',
    stage: 'Twin Peaks',
    genre: 'Alternative',
    upvotes: 1949,
    events: 1,
    followers: 1238,
    album: 'Sway',
    time: 'Friday, 1245PM',
  },
  {
    image: 'http://www.billboard.com/files/styles/article_main_image/public/media/2016-music-preview-jidenna-bb1-billboard-650.jpg',
    start: '14:10',
    end: '14:55',
    name: 'Jidenna',
    description: 'Jidenna Theodore Mobisson (born May 4, 1985), known professionally as Jidenna, is a Nigerian-American recording artist signed to Wondaland Records. In 2015, Jidenna released two singles, "Classic Man" and "Yoga", promoting the label\'s compilation EP The Eephus.',
    stage: 'Twin Peaks',
    genre: 'Hip Hop',
    upvotes: 12949,
    events: 1,
    followers: 2238,
    album: 'Sway',
    time: 'Friday, 210PM',
  },
  {
    image: 'https://media.npr.org/assets/img/2012/12/31/polica_wide-a0e6e89ed37f5aad2c078dd7cff9de8fea5272f4.jpg?s=1400',
    start: '15:40',
    end: '16:30',
    name: 'Polica',
    description: 'Poliça (often written as Polica) is an American synthpop and alternative rock band from Minneapolis founded in 2011 by Ryan Olson (production) and Channy Leaneagh (vocals/synth). Live, the group consists of Chris Bierden (bass/vocals), Drew Christopherson (drums), Ben Ivascu (drums) and Channy Leaneagh (vocals). The band have released three albums, Give You the Ghost (2012), Shulamith (2013) and United Crushers (2016) through Mom + Pop Music and tour internationally.',
    stage: 'Twin Peaks',
    genre: 'Synthpop',
    upvotes: 2349,
    events: 1,
    followers: 1338,
    album: 'Sway',
    time: 'Friday, 340PM',
  },
  {
    image: 'http://www.edmsauce.com/wp-content/uploads/2014/12/thomas-jack.jpg',
    start: '17:15',
    end: '18:05',
    name: 'Thomas Jack',
    stage: 'Twin Peaks',
    genre: 'Indie',
    upvotes: 1349,
    events: 1,
    followers: 838,
    album: 'n/A',
    time: 'Friday, 515PM',
  },
  {
    image: 'https://i.guim.co.uk/img/static/sys-images/guardian/About/General/2012/11/22/1353609924913/Grimes-010.jpg?w=460&q=55&auto=format&usm=12&fit=max&s=e294b592e0d54dbae53484376bf247bd',
    start: '18:50',
    end: '19:50',
    name: 'Grimes',
    description: 'Claire Elise Boucher (born March 17, 1988), better known by the stage name Grimes, is a Canadian singer, songwriter, music video director, and record producer. Born and raised in Vancouver, she first became involved with the underground music scene and began recording her own experimental music while attending McGill University in Montreal.',
    stage: 'Twin Peaks',
    genre: 'Synthpop',
    upvotes: 2349,
    events: 1,
    followers: 1938,
    album: 'n/A',
    time: 'Friday, 650PM',
  },
  {
    image: 'https://i.guim.co.uk/img/static/sys-images/guardian/About/General/2012/11/22/1353609924913/Grimes-010.jpg?w=460&q=55&auto=format&usm=12&fit=max&s=e294b592e0d54dbae53484376bf247bd',
    start: '18:50',
    end: '19:50',
    name: 'Grimes',
    stage: 'Twin Peaks',
    genre: 'Synthpop',
    upvotes: 2349,
    events: 1,
    followers: 1938,
    album: 'n/A',
    time: 'Friday, 650PM',
  },
  {
    image: 'http://berkeleybside.com/wp-content/uploads/2015/07/DSC_9912.jpg',
    start: '20:40',
    end: '21:55',
    name: 'J. Cole',
    description: 'And they say you can\'t go home again. Following 2011\'s Cole World: The Sideline Story and 2013\'s Born Sinner, Jermaine Lamarr Cole, aka Roc Nation rapper J. Cole, has returned to his childhood home in Fayetteville, North Carolina on his new, third album: 2014 Forest Hills Drive. Released December 9, 2014 Forest Hills Drive is a concept record about how a boy discovered his purpose, written from the perspective of a superstar rapper questioning the facets of fame.',
    name: 'J COLE',
    stage: 'Twin Peaks',
    genre: 'HIP HOP',
    upvotes: 7200,
    events: 1,
    followers: 5890,
    album: 'Forest Hills Drive',
    time: 'Friday, 840PM',
  },
  {
    image: 'http://www.thebaybridged.com/wp-content/uploads/2013/12/tumblr_mtgr2aTbZs1qgc24oo9_1280.jpg',
    start: '12:00',
    end: '12:40',
    name: 'Down and Outlaws',
    description: 'To Down and Outlaws, it\'s obvious and unavoidable. But apparently an all-for-one philosophy of songwriting and identity is an anomaly in the modern era of music. Recorded in a marathon one-week session at Studio 606, "Above Snakes" finds San Francisco\'s Down and Outlaws fine-tuning their place musically and striving to channel the restless, pissed off spirits of rock and roll history.',
    stage: 'Panhandle',
    genre: 'ALTERNATIVE',
    upvotes: 4200,
    events: 1,
    followers: 2896,
    album: 'Above Snakes',
    time: 'Friday, 1200PM',
  },
  {
    image: 'https://media.livenation.com/artists/129396/129396-show-99830.jpg?1413915421',
    start: '13:30',
    end: '14:10',
    name: 'Moon Taxi',
    description: 'Moon Taxi is an American indie-progressive rock band based in Nashville, Tennessee. The band was founded in 2006 by Trevor Terndrup (vocals, guitar), Tommy Putnam (bass), Spencer Thomson (guitar, programming), Tyler Ritter (drums), and Wes Bailey (keys) while attending Belmont University',
    stage: 'Panhandle',
    genre: 'Rock Band',
    upvotes: 2100,
    events: 1,
    followers: 1824,
    album: 'Day Breaker',
    time: 'Friday, 130PM',
  },
  {
    image: 'https://67.media.tumblr.com/9ce74f266e860681f13d0a8869d40b3c/tumblr_nlxkmb5GOv1r4gxc3o1_500.jpg',
    start: '14:55',
    end: '15:35',
    name: 'Vulfpeck',
    description: 'Vulfpeck is an American funk group founded in 2011. The band aims for a sound that is minimal, raw, and approaches that of a live performance. The band has released four EPs and a silent album on Spotify titled Sleepify – royalties from which funded the band\'s admission-free tour in 2014. The band\'s full-length album, Thrill of the Arts, was released in 2015.',
    stage: 'Panhandle',
    genre: 'American Funk',
    upvotes: 2100,
    events: 1,
    followers: 1824,
    album: 'Thrill of the Arts',
    time: 'Friday, 255PM',
  },
  {
    image: 'http://www.thatdrop.com/wp-content/uploads/2015/03/TOKiMONSTA-via-Instagram-398x400.png',
    start: '16:30',
    end: '17:10',
    name: 'Tokimonsta',
    description: 'Jennifer Lee, better known by her stage name Tokimonsta (often styled as TOKiMONSTA), is an American record producer and DJ from Los Angeles, California. She has collaborated with Thirsty Fish, Kool Keith, MNDR. & Anderson Paak.',
    stage: 'Panhandle',
    genre: 'DJ',
    upvotes: 2100,
    events: 1,
    followers: 1824,
    album: 'untz untz',
    time: 'Friday, 430PM',
  },
  {
    image: 'http://www.lh-st.com/assets/root/images/artist/lhst/05.01_LapsleySITE.jpg',
    start: '18:05',
    end: '18:45',
    name: 'LÅPSLEY',
    description: 'Holly Lapsley Fletcher (born 7 August 1996), known by the stage name Låpsley, is an English singer, songwriter, and musician. Her debut album Long Way Home was released on 4 March 2016.',
    stage: 'Panhandle',
    genre: 'Soft Stuff',
    upvotes: 2100,
    events: 1,
    followers: 1824,
    album: 'Long Way Home',
    time: 'Friday, 605PM',
  },
  {
    image: 'http://cdn1.pri.org/sites/default/files/migration/PriMigrationsDamanticWordpressAttachmentsImagesMigration/www.theworld.org/wp-content/uploads/Hiatus-kaiyote620.jpg',
    start: '19:50',
    end: '20:35',
    name: 'Hiatus Kaiyote',
    description: 'Hiatus Kaiyote is a future-soul quartet formed in Melbourne, Australia in 2011. The members are Naomi "Nai Palm" Saalfield (vocals, guitar), Paul Bender (bass), Simon Mavin (keyboards) and Perrin Moss (drums, percussion). In 2013, they were nominated for a Grammy for Best R&B Performance for their song "Nakamarra", performed with Q-Tip, but lost out to Snarky Puppy and Lalah Hathaway\'s recording "Something". The song appears on their debut album, Tawk Tomahawk, released by Flying Buddha.',
    stage: 'Panhandle',
    genre: 'FUTURE SOUL QUARTET',
    upvotes: 3100,
    events: 1,
    followers: 2824,
    album: 'Long Way Home',
    time: 'Friday, 750PM',
  },
  {
    image: 'http://s3.amazonaws.com/dostuff-production/band_alternate_photo/custom_photos/71035/customc86c6a907c8bc8035e85c1674876e700.png',
    start: '12:00',
    end: '13:30',
    name: 'Make It Funky DJs',
    stage: 'House By Heineken',
    genre: 'DJ',
    upvotes: 900,
    events: 1,
    followers: 524,
    album: 'Make It Funky',
    time: 'Friday, 1200PM',
  },
  {
    image: 'https://cdn-assets.insomniac.com/styles/event_detail_image/s3/images/artist/219_boys.jpg?itok=ZTvam0f-',
    start: '13:30',
    end: '15:00',
    name: '219 Boys',
    stage: 'House By Heineken',
    genre: 'DJ',
    upvotes: 600,
    events: 1,
    followers: 374,
    album: 'Dont You Know',
    time: 'Friday, 130PM',
  },
  {
    image: 'http://s1.minutebuzz.com/i/2014/01/1003924_627674437264849_507635481_n-L.jpg.jpg',
    start: '15:00',
    end: '16:30',
    name: 'FDVM',
    stage: 'House By Heineken',
    genre: 'DJ',
    upvotes: 600,
    events: 1,
    followers: 374,
    album: 'n/A',
    time: 'Friday, 300PM',
  },
  {
    image: 'http://s1.minutebuzz.com/i/2014/01/1003924_627674437264849_507635481_n-L.jpg.jpg',
    start: '16:30',
    end: '18:00',
    name: 'Redlight',
    stage: 'House By Heineken',
    genre: 'DJ',
    upvotes: 700,
    events: 1,
    followers: 474,
    album: 'x Colour',
    time: 'Friday, 430PM',
  },
  {
    image: 'https://img.discogs.com/DzptXqJ0VD-LEv0A6kS8E1JUJdo=/fit-in/300x300/filters:strip_icc():format(jpeg):mode_rgb():quality(40)/discogs-images/A-1271917-1360836891-3939.jpeg.jpg',
    start: '18:00',
    end: '20:00',
    name: 'Pillowtalk',
    stage: 'House By Heineken',
    genre: 'DJ',
    upvotes: 700,
    events: 1,
    followers: 474,
    album: 'Je Ne Sais Quoi',
    time: 'Friday, 600PM',
  },
  {
    image: 'http://www.thedavisdirt.com/wp-content/uploads/2014/07/OL-The-Barbary.jpg',
    start: '13:20',
    end: '14:30',
    name: 'The Romane Event',
    stage: 'The Barbery',
    genre: 'MIX',
    upvotes: 700,
    events: 1,
    followers: 474,
    album: 'n/A',
    time: 'Friday, 120PM',
  },
  {
    image: 'http://www.thedavisdirt.com/wp-content/uploads/2014/07/OL-The-Barbary.jpg',
    start: '15:00',
    end: '15:50',
    name: 'Hound Tall Discussion Series with Moshe Kasher',
    stage: 'The Barbery',
    genre: 'MIX',
    upvotes: 700,
    events: 1,
    followers: 474,
    album: 'n/A',
    time: 'Friday, 300PM',
  },
  {
    image: 'http://www.thedavisdirt.com/wp-content/uploads/2014/07/OL-The-Barbary.jpg',
    start: '16:20',
    end: '17:05',
    name: 'Natasha Leggero, John Early, and Jermaine Fowler',
    stage: 'The Barbery',
    genre: 'MIX',
    upvotes: 700,
    events: 1,
    followers: 474,
    album: 'n/A',
    time: 'Friday, 420PM',
  },
  {
    image: 'http://www.thedavisdirt.com/wp-content/uploads/2014/07/OL-The-Barbary.jpg',
    start: '17:35',
    end: '18:25',
    name: 'John Mulaney & Beth Stelling',
    stage: 'The Barbery',
    genre: 'MIX',
    upvotes: 700,
    events: 1,
    followers: 474,
    album: 'n/A',
    time: 'Friday, 535PM',
  },
  {
    image: 'http://www.thedavisdirt.com/wp-content/uploads/2014/07/OL-The-Barbary.jpg',
    start: '18:45',
    end: '19:50',
    name: 'Anthony Jeslnik, Kyle Kinane and Claudia O\'Doherty',
    description: 'Anthony Jeselnik is a stand-up comedian from Pittsburgh, Pennsylvania. Anthony starred in and created THE JESELNIK OFFENSIVE, which ran for two seasons on Comedy Central. Anthony has written for and appeared on several roasts for Comedy Central, most notably THE ROAST OF DONALD TRUMP and THE ROAST OF CHARLIE SHEEN.',
    stage: 'The Barbery',
    genre: 'MIX',
    upvotes: 700,
    events: 1,
    followers: 474,
    album: 'n/A',
    time: 'Friday, 645PM',
  },
];

export default artists;
